import ThemeProvider from "@/components/Providers/ThemeProvider";
import "./../css/globals.css";
import "./../css/grid.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="tp-BR" suppressHydrationWarning >
      <body className={`${poppins.className}`} >
        <ThemeProvider>
          <ToastContainer 
            position="top-right" 
            theme="colored"
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
